project:
  type: website

website:
  title: "Ciencia de Datos con R"
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true